INSERT IGNORE INTO ingredients_ingredient (name, category, allergens, dietary_info, created_at, updated_at, deleted_on) VALUES
('Artichoke', 'vegetables', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Asparagus', 'vegetables', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Balsamic Vinegar', 'condiments', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Barley', 'grains', '["gluten"]', '["whole-grain"]', NOW(), NOW(), NULL),
('Beets', 'vegetables', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Black Beans', 'legumes', '[]', '["vegan", "high-protein"]', NOW(), NOW(), NULL),
('Blueberries', 'fruits', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Canned Tuna', 'proteins', '["fish"]', '["high-protein"]', NOW(), NOW(), NULL),
('Chickpeas', 'legumes', '[]', '["vegan", "high-protein"]', NOW(), NOW(), NULL),
('Chocolate Chips', 'baking', '["dairy"]', '[]', NOW(), NOW(), NULL),
('Cilantro', 'herbs_and_spices', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Cloves', 'herbs_and_spices', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Coleslaw Mix', 'vegetables', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Cranberries', 'fruits', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Cream', 'dairy', '["dairy"]', '[]', NOW(), NOW(), NULL),
('Dill', 'herbs_and_spices', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Feta Cheese', 'dairy', '["dairy"]', '[]', NOW(), NOW(), NULL),
('Frozen Spinach', 'vegetables', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Ginger', 'herbs_and_spices', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Green Beans', 'vegetables', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Green Onion', 'vegetables', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Ham', 'proteins', '[]', '["high-protein"]', NOW(), NOW(), NULL),
('Hard-Boiled Eggs', 'proteins', '["egg"]', '["high-protein", "gluten-free"]', NOW(), NOW(), NULL),
('Iceberg Lettuce', 'vegetables', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Jam', 'condiments', '[]', '["gluten-free"]', NOW(), NOW(), NULL),
('Jasmine Rice', 'grains', '[]', '["gluten-free"]', NOW(), NOW(), NULL),
('Kidney Beans', 'legumes', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Leek', 'vegetables', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Maple Syrup', 'sweeteners', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL),
('Yellow Onion', 'vegetables', '[]', '["vegan", "gluten-free"]', NOW(), NOW(), NULL);
