INSERT IGNORE INTO ingredients_ingredient 
(name, category, allergens, dietary_info, price_A101, price_SOK, price_BIM, price_MIGROS, base_currency, base_unit, base_quantity, allowed_units, created_at, updated_at, deleted_on) VALUES
('Almonds', 'nuts', '["nuts"]', '["vegan","gluten-free"]', 3.00, 3.10, 2.90, 3.05, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Apricot', 'fruits', '[]', '["vegan","gluten-free"]', 0.30, 0.32, 0.28, 0.35, 'USD', 'pcs', 1, '["pcs"]', NOW(), NOW(), NULL),
('Asparagus', 'vegetables', '[]', '["vegan","gluten-free"]', 2.50, 2.40, 2.60, 2.45, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Avocado', 'fruits', '[]', '["vegan","healthy-fat"]', 1.20, 1.15, 1.30, 1.25, 'USD', 'pcs', 1, '["pcs"]', NOW(), NOW(), NULL),
('Barley', 'grains', '["gluten"]', '[]', 0.80, 0.85, 0.90, 0.75, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Beets', 'vegetables', '[]', '["vegan","gluten-free"]', 1.50, 1.45, 1.40, 1.55, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Black Beans', 'legumes', '[]', '["vegan","gluten-free"]', 2.20, 2.10, 2.15, 2.25, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Blueberries', 'fruits', '[]', '["vegan","gluten-free"]', 5.00, 4.80, 5.10, 5.25, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Brussels Sprouts', 'vegetables', '[]', '["vegan","gluten-free"]', 3.20, 3.10, 3.00, 3.25, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Cabbage', 'vegetables', '[]', '["vegan","gluten-free"]', 1.80, 1.75, 1.85, 1.90, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Cauliflower', 'vegetables', '[]', '["vegan","gluten-free"]', 2.50, 2.40, 2.60, 2.55, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Celery', 'vegetables', '[]', '["vegan","gluten-free"]', 1.90, 1.85, 2.00, 1.95, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Chia Seeds', 'seeds', '[]', '["vegan","high-fiber"]', 12.00, 11.50, 11.80, 12.20, 'USD', 'kg', 1, '["g","kg","tbsp"]', NOW(), NOW(), NULL),
('Chickpeas', 'legumes', '[]', '["vegan","gluten-free"]', 2.50, 2.40, 2.45, 2.60, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Cilantro', 'herbs_and_spices', '[]', '["vegan","gluten-free"]', 0.50, 0.55, 0.60, 0.52, 'USD', 'g', 10, '["g","kg"]', NOW(), NOW(), NULL),
('Cranberries', 'fruits', '[]', '["vegan","gluten-free"]', 4.00, 3.80, 4.10, 3.90, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Cumin', 'herbs_and_spices', '[]', '["vegan","gluten-free"]', 2.00, 1.90, 2.10, 2.05, 'USD', 'g', 10, '["g"]', NOW(), NOW(), NULL),
('Dates', 'fruits', '[]', '["vegan","gluten-free"]', 3.50, 3.30, 3.25, 3.40, 'USD', 'kg', 1, '["g","kg","pcs"]', NOW(), NOW(), NULL),
('Feta Cheese', 'dairy', '["dairy"]', '[]', 8.00, 7.50, 7.80, 7.90, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Flax Seeds', 'seeds', '[]', '["vegan","gluten-free"]', 6.50, 6.20, 6.80, 6.30, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Green Beans', 'vegetables', '[]', '["vegan","gluten-free"]', 2.80, 2.70, 2.90, 2.85, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Kale', 'vegetables', '[]', '["vegan","gluten-free"]', 3.00, 2.90, 3.10, 3.05, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Lentils', 'legumes', '[]', '["vegan","high-protein"]', 2.60, 2.55, 2.50, 2.65, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Lime', 'fruits', '[]', '["vegan","gluten-free"]', 0.40, 0.45, 0.42, 0.50, 'USD', 'pcs', 1, '["pcs"]', NOW(), NOW(), NULL),
('Mushrooms', 'vegetables', '[]', '["vegan","gluten-free"]', 2.80, 2.60, 2.90, 2.70, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Oats', 'grains', '["gluten"]', '["vegan","high-fiber"]', 1.80, 1.85, 1.75, 1.90, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Peanuts', 'nuts', '["nuts"]', '["vegan","high-protein"]', 3.50, 3.40, 3.25, 3.60, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Pineapple', 'fruits', '[]', '["vegan","gluten-free"]', 1.50, 1.55, 1.60, 1.45, 'USD', 'pcs', 1, '["pcs"]', NOW(), NOW(), NULL),
('Pumpkin', 'vegetables', '[]', '["vegan","gluten-free"]', 2.00, 1.90, 2.10, 2.05, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL),
('Raspberries', 'fruits', '[]', '["vegan","gluten-free"]', 6.50, 6.20, 6.80, 6.90, 'USD', 'kg', 1, '["g","kg"]', NOW(), NOW(), NULL);