POST http://127.0.0.1:8000/api/register/ 
Content-Type: application/json

{
  "username": "dietitianjohn154",
  "email": "dietitian.john154@example.com",
  "password": "secureDietitianPassword123",
  "usertype": "dietitian",
  "dietitian": {
    "certification_url": "https://example.com/certifications/john_certification"
  }
}
###

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "email": "savasciogluozgur@gmail.com",
  "password": "123"
}
###

POST http://127.0.0.1:8000/api/logout/
Authorization: Token a9d0cb508b5af8cb61b963decb754081c00b1b7e