POST http://127.0.0.1:8000/api/register/ 
Content-Type: application/json

{
    "username": "ozgursavascioglu",
    "email": "savasciogluozgur@gmail.com",
    "password": "securepass123",
    "usertype": "user"
}